<a href="https://colab.research.google.com/github/harshita-28/Machine-Learning-Projects/blob/main/iris_flowers_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries
 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 
#importing our iris flowers dataset
 
dataset = pd.read_csv('iris_flowers.csv')
 
#defining features and target
 
X = dataset.iloc[:, 1:4].values
Y = dataset.iloc[:,4].values

In [ ]:
#examine dataset

dataset.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  iris_setosa
1           4.9          3.0           1.4          0.2  iris_setosa
2           4.7          3.2           1.3          0.2  iris_setosa
3           4.6          3.1           1.5          0.2  iris_setosa
4           5.0          3.6           1.4          0.2  iris_setosa

In [ ]:
#finding dimensions of dataset

print("iris_flowers dataset dimensions: {}".format(dataset.shape))

iris_flowers dataset dimensions: (150, 5)


In [ ]:
#finding any null or missing points within dataset

dataset.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

In [ ]:
#encoding categorical data values

from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
print (Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
#splitting dataset into 75% Training set and 25% Test set

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split (X, Y, test_size = 0.25, random_state = 0)

In [ ]:
#Feature scaling , standardizing features

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#importing for stats

from sklearn.metrics import accuracy_score

In [ ]:
#Using KNN 

from sklearn.neighbors import KNeighborsClassifier
classifier_1 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_1.fit(X_train, Y_train)
Y_pred1 = classifier_1.predict(X_test)
print (accuracy_score(Y_test, Y_pred1))

0.9736842105263158


In [ ]:
#confusion matrix for KNN

from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(Y_test, Y_pred1)
print(cm1)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
#Using SVM with linear kernel

from sklearn.svm import SVC
classifier_2 = SVC(kernel = 'linear', random_state = 0)
classifier_2.fit(X_train, Y_train)
Y_pred2 = classifier_2.predict(X_test)
print (accuracy_score(Y_test, Y_pred2))

0.9736842105263158


In [ ]:
#confusion matrix for SVM with linear kernel

cm2 = confusion_matrix(Y_test, Y_pred2)
print(cm2)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
#Using SVM with rbf kernel

classifier_3 = SVC(kernel = 'rbf', random_state = 0)
classifier_3.fit(X_train, Y_train)
Y_pred3 = classifier_3.predict(X_test)
print(accuracy_score(Y_test, Y_pred3))

0.9736842105263158


In [ ]:
#confusion matrix for SVM with rbf kernel

cm3 = confusion_matrix(Y_test, Y_pred3)
print(cm3)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
#Using Decision Trees

from sklearn.tree import DecisionTreeClassifier
classifier_4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_4.fit(X_train, Y_train)
Y_pred4 = classifier_4.predict(X_test)
print(accuracy_score(Y_test, Y_pred4))

0.9736842105263158


In [ ]:
#confusion matrix for Decision Trees

cm4 = confusion_matrix(Y_test, Y_pred4)
print(cm4)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [ ]:
#Using Naive Bayes

from sklearn.naive_bayes import GaussianNB
classifier_5 = GaussianNB()
classifier_5.fit(X_train, Y_train)
Y_pred5 = classifier_5.predict(X_test)
print(accuracy_score(Y_test, Y_pred5))

0.9736842105263158


In [ ]:
#confusion matrix for Naive Bayes

cm5 = confusion_matrix(Y_test, Y_pred5)
print(cm5)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
